export const XSS_CORPUS: readonly string[] = [
  '<script>alert(1)</script>',
  '<img src=x onerror=alert(1)>',
  '<iframe src="javascript:alert(1)"></iframe>',
  '<object data="data:text/html,<script>alert(1)</script>"></object>',
  '<embed src="javascript:alert(1)">',
  '<svg onload=alert(1)>',
  '<svg><script>alert(1)</script></svg>',
  '<math><mtext><img src=x onerror=alert(1)></mtext></math>',
  '&#x3C;script&#x3E;alert(1)&#x3C;/script&#x3E;',
  '&lt;img src=x onerror=alert(1)&gt;',
  '[click](javascript:alert(1))',
  '[click](JaVaScRiPt:alert(1))',
  '[click](data:text/html,alert(1))',
  '[click](vbscript:alert(1))',
  '[click](file:///etc/passwd)',
  '[click](//evil.example/path)',
  '![alt](javascript:alert(1))',
  '![alt](data:image/svg+xml,<svg onload=alert(1)>)',
  '<javascript:alert(1)>',
  '<data:text/html,alert(1)>',
  '<a href="javascript:alert(1)" onclick="alert(1)">link</a>',
  '<div onmouseover="alert(1)">hover</div>',
  '<details open ontoggle="alert(1)"><summary>open</summary></details>',
  '<video><source onerror="alert(1)"></video>',
  '<form action="javascript:alert(1)"><button>go</button></form>',
  '<style>@import "javascript:alert(1)";</style>',
  '<meta http-equiv="refresh" content="0;javascript:alert(1)">',
  '`<script>alert(1)</script>`',
  '```html\n<img src=x onerror=alert(1)>\n```',
  '[nested](%6A%61%76%61%73%63%72%69%70%74%3Aalert(1))',
  '[double](%256A%2561%2576%2561%2573%2563%2572%2569%2570%2574%253Aalert(1))',
  '![entity](data:image/png;base64,PHN2ZyBvbmxvYWQ9YWxlcnQoMSk+)',
  '<svg><foreignObject><iframe src="https://evil.example"></iframe></foreignObject></svg>',
  '~~~\n<a href="javascript:alert(1)">x</a>\n~~~',
  '[autolink](https://safe.example " onmouseover="alert(1))',
  'javascript&#58;alert(1)',
  '[title](https://safe.example/%0Ajavascript:alert(1))',
];
